-- Seed 50 sample jobs - column names need double quotes for camelCase
INSERT INTO "Job" (id, source, title, company, location, description, "applyUrl", "emailContact", "scoutedAt") VALUES
('j001', 'LinkedIn', 'Senior Frontend Engineer', 'TechCorp', 'Jakarta', 'Build scalable React applications with TypeScript', 'https://techcorp.com/careers/fe-senior', 'hr@techcorp.com', NOW() - INTERVAL '5 days'),
('j002', 'JobStreet', 'Full Stack Developer', 'StartupXYZ', 'Bandung', 'Node.js + React role for growing startup', 'https://jobstreet.com/apply/startupxyz', 'jobs@startupxyz.com', NOW() - INTERVAL '3 days'),
('j003', 'LinkedIn', 'Backend Engineer', 'DataFlow', 'Surabaya', 'PostgreSQL and Fastify expertise required', 'https://dataflow.id/hire', 'recruit@dataflow.id', NOW() - INTERVAL '2 days'),
('j004', 'Kalibrr', 'DevOps Engineer', 'CloudPlatform', 'Jakarta', 'AWS, Docker, Kubernetes experience', 'https://kalibrr.com/job/cloudplatform', 'talent@cloudplatform.io', NOW() - INTERVAL '1 day'),
('j005', 'Indeed', 'Product Manager', 'SaaSCo', 'Jakarta', 'Lead product strategy for SaaS platform', 'https://indeed.com/viewjob?jk=sasco', 'pm-hiring@saasco.com', NOW()),
('j006', 'LinkedIn', 'QA Automation Engineer', 'QATeam', 'Yogyakarta', 'Selenium and Jest automation testing', 'https://qateam.co/jobs/automation', 'qa-hire@qateam.co', NOW() - INTERVAL '4 days'),
('j007', 'Glassdoor', 'UI/UX Designer', 'DesignStudio', 'Jakarta', 'Design mobile apps with Figma', 'https://glassdoor.com/job/designstudio-ux', 'design@designstudio.id', NOW() - INTERVAL '6 days'),
('j008', 'LinkedIn', 'Machine Learning Engineer', 'AILabs', 'Jakarta', 'Python, TensorFlow, computer vision', 'https://ailabs.id/careers/ml', 'ml-team@ailabs.id', NOW() - INTERVAL '7 days'),
('j009', 'JobStreet', 'Data Analyst', 'Analytics Inc', 'Bandung', 'SQL and Tableau dashboard creation', 'https://jobstreet.com/apply/analytics', 'data-hiring@analyticsinc.com', NOW() - INTERVAL '8 days'),
('j010', 'LinkedIn', 'Mobile Developer', 'MobileFirst', 'Jakarta', 'React Native cross-platform development', 'https://mobilefirst.dev/jobs', 'mobile@mobilefirst.dev', NOW() - INTERVAL '9 days'),
('j011', 'Kalibrr', 'Cloud Architect', 'CloudExperts', 'Jakarta', 'Design enterprise cloud solutions', 'https://kalibrr.com/job/cloudexperts', 'architect@cloudexperts.id', NOW() - INTERVAL '10 days'),
('j012', 'Indeed', 'Frontend Developer', 'WebDev Corp', 'Surabaya', 'Vue.js and Nuxt specialization', 'https://indeed.com/viewjob?jk=webdev', 'fe-hiring@webdevcorp.com', NOW() - INTERVAL '11 days'),
('j013', 'LinkedIn', 'Backend Engineer (Python)', 'PyTech', 'Jakarta', 'Django and FastAPI expertise', 'https://pytech.io/careers', 'py-hiring@pytech.io', NOW() - INTERVAL '12 days'),
('j014', 'Glassdoor', 'Security Engineer', 'SecureNet', 'Jakarta', 'Penetration testing and vulnerability assessment', 'https://glassdoor.com/job/securenet-sec', 'security@securenet.id', NOW() - INTERVAL '13 days'),
('j015', 'JobStreet', 'Database Administrator', 'DataCore', 'Bandung', 'PostgreSQL and MongoDB optimization', 'https://jobstreet.com/apply/datacore', 'dba@datacore.id', NOW() - INTERVAL '14 days'),
('j016', 'LinkedIn', 'Solutions Architect', 'EnterpriseSoft', 'Jakarta', 'Enterprise software design', 'https://enterprise-soft.com/hire', 'sa-hiring@enterprise-soft.com', NOW() - INTERVAL '15 days'),
('j017', 'Kalibrr', 'Frontend Engineer (Angular)', 'AngularShop', 'Yogyakarta', 'Angular and TypeScript mastery', 'https://kalibrr.com/job/angularshop', 'angular@angularshop.com', NOW() - INTERVAL '2 days'),
('j018', 'LinkedIn', 'API Developer', 'APIHub', 'Jakarta', 'REST and GraphQL API design', 'https://apihub.dev/careers/api', 'api-hiring@apihub.dev', NOW() - INTERVAL '1 day'),
('j019', 'Indeed', 'Technical Lead', 'TechLeaders', 'Jakarta', 'Lead engineering team of 10+ members', 'https://indeed.com/viewjob?jk=techleaders', 'lead@techleaders.co', NOW()),
('j020', 'LinkedIn', 'Site Reliability Engineer', 'ReliableOps', 'Bandung', 'Infrastructure and monitoring expertise', 'https://reliableops.io/jobs/sre', 'sre@reliableops.io', NOW() - INTERVAL '3 days'),
('j021', 'JobStreet', 'Quality Assurance Lead', 'QALeadership', 'Jakarta', 'Manage QA team and testing strategy', 'https://jobstreet.com/apply/qalead', 'qa-lead@qaleadership.com', NOW() - INTERVAL '4 days'),
('j022', 'LinkedIn', 'Golang Developer', 'GoSystems', 'Jakarta', 'High-performance backend systems', 'https://gosystems.id/hire', 'go-hiring@gosystems.id', NOW() - INTERVAL '5 days'),
('j023', 'Glassdoor', 'Rust Developer', 'RustTeam', 'Jakarta', 'Systems programming and embedded systems', 'https://glassdoor.com/job/rustteam', 'rust@rustteam.dev', NOW() - INTERVAL '6 days'),
('j024', 'LinkedIn', 'Java Developer', 'JavaCorp', 'Surabaya', 'Spring Boot and microservices', 'https://javacorp.id/careers', 'java-hiring@javacorp.id', NOW() - INTERVAL '7 days'),
('j025', 'Kalibrr', 'C++ Developer', 'CppStudio', 'Jakarta', 'Game engine or system software development', 'https://kalibrr.com/job/cppstudio', 'cpp@cppstudio.com', NOW() - INTERVAL '8 days'),
('j026', 'Indeed', 'iOS Developer', 'AppleDev', 'Jakarta', 'Swift and SwiftUI mobile app development', 'https://indeed.com/viewjob?jk=appledev', 'ios@appledev.id', NOW() - INTERVAL '9 days'),
('j027', 'LinkedIn', 'Android Developer', 'AndroidStudio', 'Bandung', 'Kotlin and Jetpack Compose expertise', 'https://androidstudio.dev/jobs', 'android@androidstudio.dev', NOW() - INTERVAL '10 days'),
('j028', 'JobStreet', 'Blockchain Developer', 'CryptoTech', 'Jakarta', 'Smart contracts and Solidity', 'https://jobstreet.com/apply/cryptotech', 'blockchain@cryptotech.id', NOW() - INTERVAL '11 days'),
('j029', 'LinkedIn', 'Data Engineer', 'DataWarehouse', 'Jakarta', 'Build ETL pipelines and data warehouses', 'https://datawarehouse.io/hire', 'de-hiring@datawarehouse.io', NOW() - INTERVAL '12 days'),
('j030', 'Glassdoor', 'Sales Engineer', 'SalesForce', 'Jakarta', 'Technical sales and product demos', 'https://glassdoor.com/job/salesforce-se', 'sales-eng@salesforce.id', NOW() - INTERVAL '13 days'),
('j031', 'Kalibrr', 'Technical Writer', 'DocTeam', 'Yogyakarta', 'API documentation and user guides', 'https://kalibrr.com/job/docteam', 'tech-writer@docteam.co', NOW() - INTERVAL '14 days'),
('j032', 'LinkedIn', 'Scrum Master', 'AgileCoach', 'Jakarta', 'Agile team facilitation and coaching', 'https://agilecoach.id/careers', 'sm-hiring@agilecoach.id', NOW() - INTERVAL '15 days'),
('j033', 'Indeed', 'Business Intelligence Developer', 'BITeam', 'Surabaya', 'Power BI and data visualization', 'https://indeed.com/viewjob?jk=biteam', 'bi-hiring@biteam.com', NOW() - INTERVAL '1 day'),
('j034', 'LinkedIn', 'Network Engineer', 'NetOps', 'Jakarta', 'Cisco and routing/switching expertise', 'https://netops.id/jobs/network', 'net-eng@netops.id', NOW() - INTERVAL '2 days'),
('j035', 'JobStreet', 'System Administrator', 'SysAdmin Co', 'Bandung', 'Linux server management and automation', 'https://jobstreet.com/apply/sysadmin', 'sysadmin@sysadminco.com', NOW() - INTERVAL '3 days'),
('j036', 'LinkedIn', 'Game Developer', 'GameStudio', 'Jakarta', 'Unity and C# game development', 'https://gamestudio.id/careers', 'game-dev@gamestudio.id', NOW() - INTERVAL '4 days'),
('j037', 'Glassdoor', 'AR/VR Developer', 'MetaverseLab', 'Jakarta', 'Augmented and virtual reality applications', 'https://glassdoor.com/job/metaverselab', 'vr@metaverselab.id', NOW() - INTERVAL '5 days'),
('j038', 'Kalibrr', 'Embedded Systems Engineer', 'IoTDevices', 'Surabaya', 'IoT and firmware development', 'https://kalibrr.com/job/iotdevices', 'embedded@iotdevices.com', NOW() - INTERVAL '6 days'),
('j039', 'LinkedIn', 'Computer Vision Engineer', 'VisionAI', 'Jakarta', 'Image processing and OpenCV', 'https://visionai.id/hire', 'cv-engineer@visionai.id', NOW() - INTERVAL '7 days'),
('j040', 'Indeed', 'NLP Engineer', 'LanguageTech', 'Jakarta', 'Natural language processing and transformers', 'https://indeed.com/viewjob?jk=langtech', 'nlp@languagetech.io', NOW() - INTERVAL '8 days'),
('j041', 'LinkedIn', 'Performance Engineer', 'FastApps', 'Bandung', 'Application optimization and profiling', 'https://fastapps.dev/jobs', 'perf@fastapps.dev', NOW() - INTERVAL '9 days'),
('j042', 'JobStreet', 'Release Engineer', 'DeployOps', 'Jakarta', 'CI/CD pipeline management', 'https://jobstreet.com/apply/deployops', 'release@deployops.id', NOW() - INTERVAL '10 days'),
('j043', 'LinkedIn', 'Infrastructure Engineer', 'InfraCo', 'Jakarta', 'Terraform and infrastructure as code', 'https://infraco.id/careers', 'infra-hiring@infraco.id', NOW() - INTERVAL '11 days'),
('j044', 'Glassdoor', 'Automation Engineer', 'AutomateIt', 'Yogyakarta', 'RPA and workflow automation', 'https://glassdoor.com/job/automateit', 'automation@automateit.com', NOW() - INTERVAL '12 days'),
('j045', 'Kalibrr', 'Integration Engineer', 'IntegrationHub', 'Jakarta', 'System integration and middleware', 'https://kalibrr.com/job/inthub', 'integration@inthub.id', NOW() - INTERVAL '13 days'),
('j046', 'LinkedIn', 'Platform Engineer', 'PlatformTeam', 'Jakarta', 'Internal developer platform development', 'https://platformteam.dev/hire', 'platform@platformteam.dev', NOW() - INTERVAL '14 days'),
('j047', 'Indeed', 'Search Engineer', 'SearchCo', 'Bandung', 'Elasticsearch and search optimization', 'https://indeed.com/viewjob?jk=searchco', 'search-eng@searchco.id', NOW() - INTERVAL '15 days'),
('j048', 'JobStreet', 'Observability Engineer', 'ObserveLabs', 'Jakarta', 'Monitoring, logging, and tracing systems', 'https://jobstreet.com/apply/obselabs', 'obs@obselabs.io', NOW() - INTERVAL '1 day'),
('j049', 'LinkedIn', 'Email Engineer', 'EmailPro', 'Jakarta', 'Email delivery and marketing automation', 'https://emailpro.id/jobs/email-eng', 'email-eng@emailpro.id', NOW() - INTERVAL '2 days'),
('j050', 'Glassdoor', 'WebRTC Developer', 'RTCTeam', 'Jakarta', 'Real-time communication applications', 'https://glassdoor.com/job/rtcteam', 'webrtc@rtcteam.dev', NOW() - INTERVAL '3 days');